// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemError-0]
	_ = x[ItemSyntaxError-1]
	_ = x[ItemToken-2]
	_ = x[ItemColon-3]
	_ = x[ItemSemiColon-4]
	_ = x[ItemColour-5]
	_ = x[ItemAttribute-6]
	_ = x[ItemNumber-7]
	_ = x[ItemUnit-8]
	_ = x[ItemText-9]
	_ = x[ItemWhitespace-10]
	_ = x[ItemEOF-11]
}

const _itemType_name = "ItemErrorItemSyntaxErrorItemTokenItemColonItemSemiColonItemColourItemAttributeItemNumberItemUnitItemTextItemWhitespaceItemEOF"

var _itemType_index = [...]uint8{0, 9, 24, 33, 42, 55, 65, 78, 88, 96, 104, 118, 125}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
